[phases.setup]
aptPkgs = ["libpq-dev"]
nixPkgs = ["python311"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python -m uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
